apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgCZJ/yQff17p8WePvYMRuoRIa1g+nKdB22UByWNCKg/fYs8w+PMtYXhBzOlLwt3Z8liFfpIaM6Jiu2rtRWBk1HtY6NB2I72SD1MMk8rJn0pZhD4wNymhJNB2JzEPHm5hQeXps5HYMoGNTA3ymCtMFZ232Aa/XlEePBpYDeLHkLQZOuOXvfxrjb8Ccv9PWzMjN1bxUYuV+xUrWE1VyD2xYB36TPppvTw4mJ06zAgs7Uuluw7Ng6eG6tCN/MnlCURS3jBlJBSwxO76CWOAjS4VVLfTE4G2SeaoTlBfrRbUHUfiP3OryGNre9CukyDqZ9vBUmBRiyreLs2LcOvucamX+Kcm4wAPitEH6mtY21qrWHbsPLL4cF3H0lwZ5iIeUJYJ4/3xrHDrOAwqeMziqSdtGZvODfPNsaBW88VWW4yBY2bobBjtTXVdebGM3sZz0o/y02ZsDOF2KSTYthQZ1Rzj+8l3ixRtqSTDl2QMqRMrSeYPhuQ+8lJRPytv77CPTjuZmxP8kbhVUR+vkEFlzlUp1sTpemzoPyUQn7iYbIg8Tda4EfG9tf7jiHMutGmLaqwamdPhuPNbhoCH/rYkqKGKL0E1yLsKNp9bsTjdR5J14mrdovJNunUUd+yAr8GJp63TuUWyUKHf1tvf0IL164oEhWUJxbW+k7GTqsvhP4sU3KXoZ2/PwihpH57z6ANUOTmBdVxmE8qgU4YdCL/8DkxOwTsS+uHuO4g2zKMqCqD5GXdZ4mOzdVdkqVu
    username: AgCV+czA02xjQpRf6RxkYYK9jSL2gAHd7ayhmtwJD1pWOTd+Q2XCUDqjTQtuhSk5amrdSxC/vd+zkvZZlhsFhc/hM0Gc6nJ9KvpKetr+eR/fRc9JsJeSBd1UkXq+DpdBaltbt1/0NYPyWdMcv7br1jsbR0HPjPTXpcHqhCkKcoUksKAfU4hTk9ET1z87/sjXA6ktl4gjmjOSp1lMSB2SjUQ+Gtbkm39yLx3+IoS6SaAyV7kVJYsW5wTi17GOONOges35J7++DKUKTdcI2QGjPMwOb8L1zGCZQUTelfHNeDmV3tWb4sYaNwHdNE7rIayIKlXPHdYoGx07SLd6xaryklDXu5aUDVre1YL1qdBJbgzq/bXQTqHDZ32PV7Vh2YkKikV/jZZOSIT16VrVqTicA/D2kSx1faOJFUzRLKxVDFANgq8fxWyRtNKh3UR7C0o9wvxyNSNnUJqUBGgiQHFaJhM5MgrHC2OltE8b4ipzdnBytF1tAp8JHc8iI7H4l53rCQjP3uBwTDF3gyKxFjoAlIYVGz3bBhyHe5FeeMDeNpgkfSPeqXGxrNVeLOXrdEe57OBFyQLgHil5I7diLH/+lFtZlW3X44eS2N56AaWVeKQyyJHQS6jEQ0XlQ8xXWTzS0nQF/7VjOcI19m68iApIGQGdMRFXrwppXf4b+XIYJYeWTdXQ3TfAbsXXyV9QNYrAefBt5UOloKmbpUBPQJnpUg==
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

