apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgChAC3rlFSGt+g29Ojm807Agj1qK3px0/B2Tbq7D5oPFPVSLN6cwRZG/jtkzSu+1WY/bd4WshYN6AnU166KFywfG8IemqoOH4JSQwnoGFEo8/SBGwSs39tSdDsllBBhAxnkC0Yp1GQsy539xMAolMQKIKqozLl129rdLfuZB+mhUuRCNw1yz5gjYBfNkZF3kZ9L9pWTblXUTBRCuP5zSik6Kdrce4/T8dP6kSRsAEdMtDLYhXfs6Z65UU5bwU7BbXCIwN0MDdkXumY1ZX9wnAwmQb9nWfVy/BMSlCSOjU9JNO3Dx7CfKFP7T0yimBBRCZFq6YxYsVW/FiIx2pIFh7s/3n2YsbhAYm2lak8u/vGld3LvLLpJw79zwCwWdUMiNd4HjOyoSahB/MDtl6lpE3g95NFbPTMJLwyP/+6htCk+xsmvAB57JN62Hpy9Yjuf/BkX5/szUpt/l3W+AfWvGEsYuHd5bDtusNgU8WkieiiKXzVSwI7UvWpUaYfooris7DBZYvkAgk3UYWYXyQR2Wzzhc+87/f5rpc3Re8NA7ZK+G/LyipkeCcfpuUe60vKEgTCvdQXJm9Qn95bwYA6NYv9FQWr4dQ+UPAa257Mj2imqsdqMeTb2gWz+2zH4KcSdnCBUbUF/WBrUITMT6HRfzbMsoYHyYF8ZzuP+mhibJEX8fMNUOgQmlhPJoP1QnNmEvDaRvwQ49GBtd6yItmXD+gQSeJDIsrLRDk0CvOFpJetLiTLWWqQqT1NEf+l8wQWmShAmTeA9td0nq5DE3UmnKahb0G6G2kc6ZvfumiGALm9UOkkb8bE/FsA/B6XK6wr4hxwp6u+euVH9VCSkzbRXh6UPthpyu0CaLBJMWqezQBtiJ4BB6Gf0pGx/JqN+u6NrbD/NXFhou/rBts6aqYW030qVuM7YOjtpt3LX1Cc62Hi1dGQ7f646R3Bsj8tPsdlqGyg=
    IBM_ENTITLED_REGISTRY_USER: AgBLJX958yA03UWnfjfF6aPZdpAdRc9/UjUNZa8D5G7+MlbH6rYxqKkFiadkLRPi7o9UORXj9PC4tQ8FOYJT0L/NDVVya7ZpU6FztwuvKUbRFwXDqnOzHlggzUgLmYLn5D7D/NiQWzr0dxfOsW7jXknc2JNXtI4QmgsPVFMLCri2r/r/bcVtuSUdMheSTLJtfaGxWzNYQv0O/xmzZDueZrl7tZu7SRlE/TRZF9GQaVkgA+xEVOPIZvWkUn+/OkepMnH73O49s9luyMLvwE7z80UDSmMxB3yv/iobF8rbqfc+0GXzwV0wvG36lKHvfEnk/Lt2zi2LPaN0wudmsfaeMg3muywRx3SyLhK4qqc8TsNr5Y4rhGM1G8/R2/Ao74ihKRj335clasFyf7iqrwlrrbRZ0NMJTePITjw/fXxGJj9l3uHJonVcdBpdESuL87DRbo19z8hKf1vGvv6bwJcJ8Lpn3RTMVw0A7Inp/X9riDMDQ7AUOl3yfDFXosWx+O0RUNdxqrP+e80pIoq+mg/HJxZPHveiQCvsB8oyChwo8MDoiKXi7cEgFxxKWX31rXHja3dOnEqY4AIMdzuQeJFcFozd6POlMp1DUShbIkVt4dynJpSSbj7jCfGnfeQFYoz+zTsY4f2QyLMCxWIxCsL0abGpzahRrCIMXq+gNWP4mNaneEjbjHKnkTozBTFTohytUXHEfA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

